/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

// Per al metode carregaTaula()
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;

import javax.swing.JOptionPane;
import projecte.gui.projecte1;
import projecte.gui.Boss;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;


/**
 *
 * @author alumne
 */
public class GUI extends javax.swing.JFrame {

    
    private static int filaSel=-1;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        inicialitzarComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        casellaNom = new javax.swing.JTextField();
        casellaJoc = new javax.swing.JTextField();
        casellaZona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        casellaAtac = new javax.swing.JTextField();
        casellaTamany = new javax.swing.JTextField();
        casellaAnimes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bAfegir = new javax.swing.JButton();
        bMod = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        casellaDesc = new javax.swing.JEditorPane();
        bExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 16, 462, 269);
        getContentPane().add(casellaNom);
        casellaNom.setBounds(556, 130, 130, 25);
        getContentPane().add(casellaJoc);
        casellaJoc.setBounds(556, 160, 130, 25);
        casellaJoc.getAccessibleContext().setAccessibleName("");

        getContentPane().add(casellaZona);
        casellaZona.setBounds(556, 190, 130, 25);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("<html><font color=\"white\">Nom:</font></html>");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setPreferredSize(new java.awt.Dimension(78, 15));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(472, 134, 78, 15);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("<html><font color=\"white\">Joc:</font></html>");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setPreferredSize(new java.awt.Dimension(78, 15));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(472, 164, 78, 15);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("<html><font color=\"white\">Zona:</font></html>");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setPreferredSize(new java.awt.Dimension(78, 15));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(472, 194, 78, 15);
        getContentPane().add(casellaAtac);
        casellaAtac.setBounds(556, 220, 130, 25);
        getContentPane().add(casellaTamany);
        casellaTamany.setBounds(556, 250, 130, 25);
        getContentPane().add(casellaAnimes);
        casellaAnimes.setBounds(556, 280, 130, 25);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("<html><font color=\"white\">Tipus atac:</font></html>");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(472, 225, 78, 15);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("<html><font color=\"white\">Tamany:</font></html>");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setPreferredSize(new java.awt.Dimension(78, 15));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(472, 254, 78, 15);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("<html><font color=\"white\">Animes:</font></html>");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setPreferredSize(new java.awt.Dimension(78, 15));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(472, 285, 78, 15);

        jLabel7.setText("<html><font color=\"white\">Descripció:</font></html>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 291, 78, 15);

        bAfegir.setText("Afegir");
        bAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfegirActionPerformed(evt);
            }
        });
        getContentPane().add(bAfegir);
        bAfegir.setBounds(10, 430, 72, 31);

        bMod.setText("Modificar");
        bMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModActionPerformed(evt);
            }
        });
        getContentPane().add(bMod);
        bMod.setBounds(130, 430, 95, 31);

        bDel.setText("Eliminar");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        getContentPane().add(bDel);
        bDel.setBounds(290, 430, 86, 31);

        casellaDesc.setBackground(new java.awt.Color(69, 73, 74));
        casellaDesc.setPreferredSize(new java.awt.Dimension(120, 21));
        jScrollPane2.setViewportView(casellaDesc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 310, 679, 110);

        bExit.setText("Sortir");
        bExit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(620, 430, 70, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/src/nito.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 700, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void inicialitzarComponents() {
        
        //Insereix un títol i un icono a la finestra
        this.setTitle("DS3 Bosses 1.0");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("src/artorias.png")));
        
        bDel.setEnabled(false);
        bMod.setEnabled(false);
        
        // Carrega el fitxer guardat a l'array del projecte
        projecte1.inicialitzar();
        
        carregaTaula(new String[]{"Fila","Nom","Joc","Zona","Atac","Tamany","Animes","Descripcio"}, transformaDades(projecte1.getArray()), taula);

    }
        
    public static void carregaTaula(String[] nomCols, Object[][] dades, JTable taula) {

        //Mirem si han passat columnes i dades. En cas contrari sortim
        if (nomCols == null || dades == null) {
            return;
        }

        //Variables locals
        Vector columnNames = new Vector();
        Vector data = new Vector();
        DefaultTableModel model;

        //Anotem el nº de columnes a mostrar
        int ncamps = nomCols.length;

        //Recorrem l'array de noms de columna i els posem com a columnes de la taula
        for (String s : nomCols) {
            columnNames.addElement(s);
        }

        //Si hi ha algun element a l'array de dades omplim la taula
        if (dades.length != 0) {

            for (int i = 0; i < dades.length; i++) {
                Vector row = new Vector(ncamps);
                for (int j = 0; j < dades[i].length; j++) {
                    row.add(dades[i][j]);
                }
                data.addElement(row);
            }
        }

        //Per no poder modificar les cel·les de la taula
        model = new DefaultTableModel(data, columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        taula.setModel(model);

        TableColumn column;
        for (int i = 0; i < taula.getColumnCount(); i++) {
            column = taula.getColumnModel().getColumn(i);
            column.setMaxWidth(250);
        }
    }

    private static Object[][] transformaDades(Boss[] dades) {
        
          Object[][] result = new Object[dades.length][8];

          
          int omplits=0;
          
          for (int i = 0; i < dades.length; i++) {
            if(dades[i].isOmplit()) {
                result[omplits][0]=i;
                result[omplits][1]=dades[i].getNom();
                result[omplits][2]=dades[i].getAparicio();
                result[omplits][3]=dades[i].getZona();
                result[omplits][4]=dades[i].getAtac();
                result[omplits][5]=dades[i].getTamany();
                result[omplits][6]=dades[i].getAnimes();
                result[omplits][7]=dades[i].getDesc();
                omplits++;
            }
        }
        return Arrays.copyOf(result,omplits);
    }
    
    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        // TODO add your handling code here:
        
        filaSel=taula.getSelectedRow();
        
        if(filaSel==-1){    
            //Si no han seleccionat cap fila desactivo els botons de borrar i modificar
            bDel.setEnabled(false);
            bMod.setEnabled(false);
            
            //Poso les caselles en blanc
            casellaNom.setText("");
            casellaJoc.setText("");
            casellaZona.setText("");
            casellaAtac.setText("");
            casellaTamany.setText("");
            casellaAnimes.setText("");
            casellaDesc.setText("");
        } else {
            //Si han seleccionat alguna fila activo els botons de borrar i modificar
            bDel.setEnabled(true);
            bMod.setEnabled(true);
            
            //Actualizo les caselles en la informació de la fila seleccionada
            casellaNom.setText((String)taula.getValueAt(filaSel, 1));
            casellaJoc.setText(String.valueOf(taula.getValueAt(filaSel, 2)));
            casellaZona.setText((String)taula.getValueAt(filaSel, 3));
            casellaAtac.setText(String.valueOf(taula.getValueAt(filaSel, 4)));
            casellaTamany.setText(String.valueOf(taula.getValueAt(filaSel, 5)));
            casellaAnimes.setText(String.valueOf(taula.getValueAt(filaSel, 6)));
            casellaDesc.setText((String)taula.getValueAt(filaSel, 7));
        }
    }//GEN-LAST:event_taulaMouseClicked

    /**
     * Al afegir o eliminar un nou element, la línia de selecció es mou,
     * d'aquesta manera es poden eliminar línies de forma consecutiva i que
     * quan s'en creïn de noves, l'última quedi automàticament seleccionada.
     * @param sel Línia seleccionada
     */
    public void rowSel(int sel) {
        
        Boss[] array = projecte1.getArray();
        
        int i;
        for (i = 0; i < array.length && array[i].isOmplit(); i++);
        
        taula.changeSelection((sel==i?--sel:sel), 0, false, false);
        
        filaSel=sel;
        
    }
    
    /**
     * Revisa que el text entrat sigui un double
     * @param cas String a comprovar
     * @return
     */
    public static boolean isDouble(String cas) {
        try {
            Double.parseDouble(cas);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    /**
     * Revisa que el text entrat sigui un Integer
     * @param cas String a comprovar
     * @return
     */
    public static boolean isInt(String cas) {
        
        try {
            Integer.parseInt(cas);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
        
    }
    
    //Revisa que totes les dades, ja siguin inserides o modificades, siguin correctes
    private boolean dadesCorrectes() {
        
        //Crea una llista que s'utilitzarà per comprovar el valor de la "casellaAtac"
        List atacs = Arrays.asList("a","m","c");
        
        try {
            //Cada condició llança una excepció personalitzada que es llegida per la funció "Exepcio",
            //que es troba dins el fitxer "Excepcio.java", i aquest llança el missatge d'error 
            //que tracta l'error de forma específica
            if (casellaNom.getText().trim().length()<1) throw new Excepcio(0,"Nom");
            if (casellaJoc.getText().trim().length()<1) throw new Excepcio(0,"Joc");
            if (casellaZona.getText().trim().length()<1) throw new Excepcio(0,"Zona");
            if (casellaAtac.getText().trim().length()<1) throw new Excepcio(0,"Atac");
            if (casellaAtac.getText().trim().length()>1) throw new Excepcio(2,"");
            if (casellaTamany.getText().trim().length()<1) throw new Excepcio(0,"Tamany");
            if (casellaAnimes.getText().trim().length()<1) throw new Excepcio(0,"Animes");
            if (casellaDesc.getText().trim().length()<1) throw new Excepcio(0,"Desc");
            if (Integer.valueOf(casellaJoc.getText())<1 || Integer.valueOf(casellaJoc.getText())>3) throw new Excepcio(1,"");
            if (!(atacs.contains(String.valueOf(casellaAtac.getText().charAt(0))))) throw new Excepcio(2,"");
            if (!isDouble(casellaTamany.getText())) throw new Excepcio(3,"");
            if (!isInt(casellaAnimes.getText())) throw new Excepcio(3,"");
            
        } catch (Excepcio ex) {
            return false;
        }
        
        return true;
    }
    
    private void bModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModActionPerformed
        // TODO add your handling code here:
        
        //Si les dades no són correctes surt de la funció i no fa la modificació
        if(!dadesCorrectes()) return;
                
        int sel = (int)taula.getValueAt(filaSel, 0);
        Boss[] array = projecte1.getArray();
        
        array[sel].setNom(casellaNom.getText().trim());
        array[sel].setAparicio(Integer.valueOf(casellaJoc.getText()));
        array[sel].setZona(casellaZona.getText().trim());
        array[sel].setAtac(casellaAtac.getText().charAt(0));
        array[sel].setTamany(Double.valueOf(casellaTamany.getText()));
        array[sel].setAnimes(Integer.valueOf(casellaAnimes.getText()));
        array[sel].setDesc(casellaDesc.getText().trim());
        
        carregaTaula(new String[]{"Fila","Nom","Joc","Zona","Atac","Tamany","Animes","Descripcio"}, transformaDades(projecte1.getArray()), taula);
    }//GEN-LAST:event_bModActionPerformed

    //Tanca el programa amb el botò "Sortir" del programa
    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        
        //Carrega les dades de l'array al fitxer de guardat i tanca el programa
        projecte1.sortirPrograma();
        System.exit(1);
    }//GEN-LAST:event_bExitActionPerformed

    // Tanca el programa amb la creueta de la finestra
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        //Carrega les dades de l'array al fitxer de guardat i tanca el programa
         projecte1.sortirPrograma();   
    }//GEN-LAST:event_formWindowClosing

    private void bAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfegirActionPerformed
        // TODO add your handling code here:
        
        //Si les dades no són correctes surt de la funció i no afegeix el nou valor
        if(!dadesCorrectes()) return;
        
        Boss[] array = projecte1.getArray();
        int sel;
        for (sel = 0; sel < array.length && array[sel].isOmplit(); sel++); //busca la primera casella buida
        
        try {
            array[sel].setNom(casellaNom.getText().trim()); 
            array[sel].setAparicio(Integer.valueOf(casellaJoc.getText().trim()));
            array[sel].setZona(casellaZona.getText().trim());
            array[sel].setAtac(casellaAtac.getText().trim().charAt(0));
            array[sel].setTamany(Double.valueOf(casellaTamany.getText().trim()));
            array[sel].setAnimes(Integer.valueOf(casellaAnimes.getText().trim()));
            array[sel].setDesc(casellaDesc.getText().trim());
            array[sel].setOmplit(true);
            
            carregaTaula(new String[]{"Fila","Nom","Joc","Zona","Atac","Tamany","Animes","Descripcio"}, transformaDades(projecte1.getArray()), taula);

            rowSel(sel);
            
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Totes les caselles disponibles estan plenes (" + projecte1.getMaxBoss() + "/" + projecte1.getMaxBoss() +").\nElimina un valor per insertar un de nou", "Error d'inserció", JOptionPane.WARNING_MESSAGE);

        }
           
    }//GEN-LAST:event_bAfegirActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        
        Boss[] array = projecte1.getArray();
        int sel = (int)taula.getValueAt(filaSel, 0);
        
        // Marca la línia seleccionada com a buida
        array[sel].setOmplit(false);
        
        // Reordena l'array del projecte i el recarrega actualitzat a la taula
        projecte1.reordena();
        carregaTaula(new String[]{"Fila","Nom","Joc","Zona","Atac","Tamany","Animes","Descripcio"}, transformaDades(projecte1.getArray()), taula);
        
        rowSel(sel);
        
    }//GEN-LAST:event_bDelActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAfegir;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bMod;
    private javax.swing.JTextField casellaAnimes;
    private javax.swing.JTextField casellaAtac;
    private javax.swing.JEditorPane casellaDesc;
    private javax.swing.JTextField casellaJoc;
    private javax.swing.JTextField casellaNom;
    private javax.swing.JTextField casellaTamany;
    private javax.swing.JTextField casellaZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable taula;
    // End of variables declaration//GEN-END:variables
}
